### ISSUE TITLE
Error after NFZ crash 

### ISSUE THREAD

**Issue by ko5mi** [gilek/ewus#5]
After crash NFZ service in 19.04.2021 i have got  error:

Fatal error: Uncaught Exception: Nie można pobrać informacji o identifikatorze sesji.
--

**Comment by mariuszkostecki** [comment]
Remove ?wsdl suffix from service URLs in file \src\server\ServerBroker.php and fix the url because it should be ServiceBroker instead SerwerBroker at the end of adress in line 17.
If you use tests you should do the same in  \tests\EndToEnd\TestServiceBroker.php and \tests\Functional\Driver\NusaopDriverTest.php

**Comment by gilek** [comment]
@mariuszkostecki thanks for pointing the errors. Fix has been merged:)

**Comment by ko5mi** [comment]
I must also remove ?wsdl in file  file \src\server\ServerBroker.php in line 20 return 'https://ewus.nfz.gov.pl/ws-broker-server-ewus/services/Auth';

It's work again
